title: "Haoyang He"
email: "haoyangh@mun.ca"
description: "PhD Student at Memorial University of Newfoundland"
baseurl: "" 
url: "https://haoyang-he.github.io"

theme: minima
plugins:
  - jekyll-feed
